export const filterCategories = [
  {
    displayName: 'Diameter',
    fqlxKey: 'diameterPlatform',
    prefix: 'Ø',
    suffix: 'mm',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Length',
    fqlxKey: 'length',
    prefix: '',
    suffix: 'mm',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Neck Height',
    fqlxKey: 'lengthNeck',
    prefix: '',
    suffix: 'mm',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Implant Line',
    fqlxKey: 'implantLine',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Type',
    fqlxKey: 'level',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Material',
    fqlxKey: 'material',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
];
