export const filterCategories = [
  {
    displayName: '',
    fqlxKey: 'labScrew',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Lab Screw'],
  },
  {
    displayName: '',
    fqlxKey: 'implantReplica',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Implant Replica'],
  },
  {
    displayName: '',
    fqlxKey: 'screwdriver',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Screw Driver'],
  },
  {
    displayName: '',
    fqlxKey: 'orientationAid',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Orientation Aid'],
  },
  {
    displayName: '',
    fqlxKey: 'protectionAid',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Protection Aid'],
  },
  {
    displayName: '',
    fqlxKey: 'clampingAid',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: ['Clamping Aid'],
  },
];
