export const filterCategories = [
  {
    displayName: 'Abutment Line',
    fqlxKey: 'abutmentLine',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  // {
  //   displayName: 'Indication',
  //   fqlxKey: 'indication',
  //   prefix: '',
  //   suffix: '',
  //   dataType: 'string',
  //   options: [],
  // },
  {
    displayName: 'Material',
    fqlxKey: 'material',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Gingiva Height',
    fqlxKey: 'gingivaHeight',
    prefix: '',
    suffix: 'mm',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Implant Line',
    fqlxKey: 'implantline',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Prosthetic Height',
    fqlxKey: 'prostheticHeight',
    prefix: '',
    suffix: 'mm',
    dataType: 'string',
    options: [],
  },
];
