export const filterCategories = [
  {
    displayName: 'Retention',
    fqlxKey: 'retention',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Platform Switch',
    fqlxKey: 'platformSwitch',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Angle',
    fqlxKey: 'angle',
    prefix: '',
    suffix: '°',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Material',
    fqlxKey: 'material',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
  {
    displayName: 'Gingiva Height',
    fqlxKey: 'heightsGingiva',
    prefix: '',
    suffix: 'mm',
    dataType: 'number',
    options: [],
  },
  {
    displayName: 'Abutment Line',
    fqlxKey: 'abutmentLine',
    prefix: '',
    suffix: '',
    dataType: 'string',
    options: [],
  },
];
